### ISSUE TITLE
Edit Create orders not listed in order

### ISSUE THREAD

**Issue by jackkrooss** [tulip/ppe-logistics#207]
Not a huge big deal, but when creating orders with multiple line items the line items are not listed in numerical order:

![image](https://user-images.githubusercontent.com/64096573/87331630-224e3500-c4ef-11ea-8b3a-7db97cd071a7.png)

**Comment by jackkrooss** [comment]
![image](https://user-images.githubusercontent.com/64096573/87331859-896be980-c4ef-11ea-87df-acdac1b6bebe.png)

**Comment by ianslai** [comment]
I ended up modifying the Connector SQL directly to add `ORDER BY orderline ASC` as that was easier.

I also fixed a similar issue in the Order Manager screen (Selected Order Detail).  That would have taken a long time to fix the "right way" by adding a new Connector because the connector to load the order was tied to every single invisible button.
