### ISSUE TITLE
Create Order not filling Delivery Address on Order Screen

### ISSUE THREAD

**Issue by AmyLee1920** [tulip/ppe-logistics#47]
Created order MO219 with 4 Arborway Drive. Scituate, MA 02066 as address. Looked at newly created order on Orders screen and it was associated with 204 E Chestnut St, Independence, KS 67301, USA address? This could be easily missed by a CSR if order screen does not populate with the address provided on the Create Order screen.

**Comment by markfreedmantulip** [comment]
this specific issue is resolved - but i am going to create a new issue to handle to get after the root cause - google API is trying to find a match but if someone enters in "123" for an address, it will use some alogrithm to return "Exner St, Coffeyville, KS 67337, USA"

if you type in nothing, it returns empty. so CSRs should be made aware that there is an address lookup occurring as a short term containment measure.
